// Simple object to push
export interface MessageInput {
  content: string;
  createdAt: Date;
}

// Full Mongoose document type (auto-generated by Mongoose)
export interface MessageDocument {
  _id: string;
  content: string;
  createdAt: Date;
  // ... plus Mongoose internal props
}
